import MainLayout from "@/layouts/MainLayout";
import { Inter } from "next/font/google";
import "../styles/global.css";
import MainSideMenu from "@/layouts/side-menu";
import ChatContainer from "@/components/chat-container";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Chapar 🏇",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <section className="w-screen h-screen flex py-3 bg-black">
          <MainSideMenu />

          <div className="w-[calc(100vw-8rem)]">{children}</div>
        </section>
      </body>
    </html>
  );
}
